server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

# database setting
spring:
  application:
    name: main-service

#  profiles:
#    actice: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: root   #database username
    #    password: ZS19960203ryf #database password
    #    url: jdbc:mysql://localhost:3306/mybbs?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

    username: Areca   #database username
    password: ZS19960203ryf #database password
    url: jdbc:mysql://mybbs-rds.cxosoegc4d6i.us-east-1.rds.amazonaws.com:3306/MyBBS-v2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # 配置Hibernate
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.bbsv2.main.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


# AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    stack:
      auto: false
    region:
      auto: false
      static: us-east-1

application:
  bucket:
    name: shi1stbuckt



# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#ip: localhost