server:
  port: 9091
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false


spring:
  application:
    name: account-service

  #  profiles:
  #    actice: dev

  # database setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Areca   #database username
    password: ZS19960203ryf #database password
    url: jdbc:mysql://mybbs-rds.cxosoegc4d6i.us-east-1.rds.amazonaws.com:3306/UserDB?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8

  cache:
    type: redis
  redis:
    host: localhost # 本地开发时是 localhost，部署到 EC2 时填写 Redis 实例的内网 IP
    port: 6379 # Redis default port
    password: # 如果 Redis 配置了密码，在这里填写
    database: 0     # 使用的 Redis 数据库编号

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # 配置Hibernate
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:10086/eureka
      defaultZone: http://localhost:10086/eureka/

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.bbsv2.common.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


## AWS S3
#cloud:
#  aws:
#    credentials:
#      access-key: ${AWS_ACCESS_KEY_ID}
#      secret-key: ${AWS_SECRET_ACCESS_KEY}
#    stack:
#      auto: false
#    region:
#      auto: false
#      static: us-east-1
#
#application:
#  bucket:
#    name: shi2stbuckt



# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#ip: localhost